phone:
  port: 49998
  bot:
    interruptable: False
text:
  port: 59998
bot:
  kb:
    switch: True
    threshold: 1.0
    recommend:
      switch: True
      max_items: 10
    mysql:
      host: "118.190.53.158"
      port: "3306"
      user: "root"
      password: "rbjf_DEV123"
      database: "es_db"
    sync_period: 5
