bot:
  intent_recognition:
    similarity:
      switch: False
      min_similarity: 0.93
  kg:
    switch: True
    min_score: 16
    recommend:
      switch: True
      max_items: 4
    es:
      address: '127.0.0.1:9200'
      index: '95598'
      table: 'question'
    neo4j:
      address: 'http://127.0.0.1:7474'
      username: 'neo4j'
      password: '123456'
phone:
  port: 49999
  bot:
    interruptable: False
text:
  port: 59999
