bot:
  fwd:
    patient: 3
    switch: false
  intent_recognition:
    classifier:
      min_confidence: 0.93
      model: bert
      switch: true
    similarity:
      min_similarity: 0.9
      model: bert-base-chinese-mean-csts
      switch: false
  kb:
    es:
      port: '9200'
    recommend:
      max_items: 10
      switch: true
    switch: true
    sync:
      mysql:
        database: callcenter
        host: 10.72.0.82
        password: 1qaz@WSX
        port: '3306'
        user: root
      period: 10
    threshold: 1.0
  kg:
    es: null
    min_score: 15
    neo4j: null
    recommend:
      max_items: 3
      switch: false
    switch: false
crs:
  port: 59999
  route:
    '01': http://127.0.0.1:49995
    '02': http://127.0.0.1:49994
    '03': http://127.0.0.1:59995
    '04': http://127.0.0.1:59994
    09: http://127.0.0.1:41217
    '10': http://127.0.0.1:38679
phone:
  asr:
    record_dir: https://tasi-callcenter-audio-record.oss-cn-beijing.aliyuncs.com/ASR/
  bot:
    interruptable: false
    lock_before_fwd: false
    save_result:
      switch: false
      url: http://39.99.186.66:8001/api/robot/resultSave
  port: 49999
  postgresql:
    client_encoding: utf-8
    connect_timeout: 5
    dbname: visualization
    host: 47.93.120.246
    password: 305Cm@TFg3u70N8Q
    port: '5432'
    switch: false
    user: postgres
text:
  port: 59999
text-sgcc:
  keyboard_access: true
  port: 19999
